name: Notify Discord on Release

on:
  release:
    types: [published]
  workflow_dispatch:  # Allow manual trigger from GitHub Actions UI

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}  # Ensure your webhook URL is set in secrets
        run: |
          response=$(curl -H "Content-Type: application/json" \
          -d "{
                \"content\": \"## 🚀 New Pre-Release Version 🚀 \n\n**Version:** ${{ github.event.release.tag_name }} \n\n**Release Notes:** \n\`\`\`${{ github.event.release.body }}\`\`\` \n\n**Download it here:** https://bit.ly/3ZPH5NR\"
              }" \
          $DISCORD_WEBHOOK_URL)
          echo "Response from Discord: $response"
